//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientConsole.Xuly {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Xuly.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name CauAResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CauA", ReplyAction="*")]
        ClientConsole.Xuly.CauAResponse CauA(ClientConsole.Xuly.CauARequest request);
        
        // CODEGEN: Generating message contract since element name CauBSoChanResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CauBSoChan", ReplyAction="*")]
        ClientConsole.Xuly.CauBSoChanResponse CauBSoChan(ClientConsole.Xuly.CauBSoChanRequest request);
        
        // CODEGEN: Generating message contract since element name CauBSoLeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CauBSoLe", ReplyAction="*")]
        ClientConsole.Xuly.CauBSoLeResponse CauBSoLe(ClientConsole.Xuly.CauBSoLeRequest request);
        
        // CODEGEN: Generating message contract since element name SNTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SNT", ReplyAction="*")]
        ClientConsole.Xuly.SNTResponse SNT(ClientConsole.Xuly.SNTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CauARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CauA", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.CauARequestBody Body;
        
        public CauARequest() {
        }
        
        public CauARequest(ClientConsole.Xuly.CauARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CauARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int c;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int d;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int e;
        
        public CauARequestBody() {
        }
        
        public CauARequestBody(int a, int b, int c, int d, int e) {
            this.a = a;
            this.b = b;
            this.c = c;
            this.d = d;
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CauAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CauAResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.CauAResponseBody Body;
        
        public CauAResponse() {
        }
        
        public CauAResponse(ClientConsole.Xuly.CauAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CauAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientConsole.Xuly.ArrayOfAnyType CauAResult;
        
        public CauAResponseBody() {
        }
        
        public CauAResponseBody(ClientConsole.Xuly.ArrayOfAnyType CauAResult) {
            this.CauAResult = CauAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CauBSoChanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CauBSoChan", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.CauBSoChanRequestBody Body;
        
        public CauBSoChanRequest() {
        }
        
        public CauBSoChanRequest(ClientConsole.Xuly.CauBSoChanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CauBSoChanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int c;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int d;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int e;
        
        public CauBSoChanRequestBody() {
        }
        
        public CauBSoChanRequestBody(int a, int b, int c, int d, int e) {
            this.a = a;
            this.b = b;
            this.c = c;
            this.d = d;
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CauBSoChanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CauBSoChanResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.CauBSoChanResponseBody Body;
        
        public CauBSoChanResponse() {
        }
        
        public CauBSoChanResponse(ClientConsole.Xuly.CauBSoChanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CauBSoChanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CauBSoChanResult;
        
        public CauBSoChanResponseBody() {
        }
        
        public CauBSoChanResponseBody(string CauBSoChanResult) {
            this.CauBSoChanResult = CauBSoChanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CauBSoLeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CauBSoLe", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.CauBSoLeRequestBody Body;
        
        public CauBSoLeRequest() {
        }
        
        public CauBSoLeRequest(ClientConsole.Xuly.CauBSoLeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CauBSoLeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int c;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int d;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int e;
        
        public CauBSoLeRequestBody() {
        }
        
        public CauBSoLeRequestBody(int a, int b, int c, int d, int e) {
            this.a = a;
            this.b = b;
            this.c = c;
            this.d = d;
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CauBSoLeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CauBSoLeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.CauBSoLeResponseBody Body;
        
        public CauBSoLeResponse() {
        }
        
        public CauBSoLeResponse(ClientConsole.Xuly.CauBSoLeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CauBSoLeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CauBSoLeResult;
        
        public CauBSoLeResponseBody() {
        }
        
        public CauBSoLeResponseBody(string CauBSoLeResult) {
            this.CauBSoLeResult = CauBSoLeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SNTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SNT", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.SNTRequestBody Body;
        
        public SNTRequest() {
        }
        
        public SNTRequest(ClientConsole.Xuly.SNTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SNTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int c;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int d;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int e;
        
        public SNTRequestBody() {
        }
        
        public SNTRequestBody(int a, int b, int c, int d, int e) {
            this.a = a;
            this.b = b;
            this.c = c;
            this.d = d;
            this.e = e;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SNTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SNTResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClientConsole.Xuly.SNTResponseBody Body;
        
        public SNTResponse() {
        }
        
        public SNTResponse(ClientConsole.Xuly.SNTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SNTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientConsole.Xuly.ArrayOfInt SNTResult;
        
        public SNTResponseBody() {
        }
        
        public SNTResponseBody(ClientConsole.Xuly.ArrayOfInt SNTResult) {
            this.SNTResult = SNTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ClientConsole.Xuly.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ClientConsole.Xuly.ServiceSoap>, ClientConsole.Xuly.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsole.Xuly.CauAResponse ClientConsole.Xuly.ServiceSoap.CauA(ClientConsole.Xuly.CauARequest request) {
            return base.Channel.CauA(request);
        }
        
        public ClientConsole.Xuly.ArrayOfAnyType CauA(int a, int b, int c, int d, int e) {
            ClientConsole.Xuly.CauARequest inValue = new ClientConsole.Xuly.CauARequest();
            inValue.Body = new ClientConsole.Xuly.CauARequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            inValue.Body.d = d;
            inValue.Body.e = e;
            ClientConsole.Xuly.CauAResponse retVal = ((ClientConsole.Xuly.ServiceSoap)(this)).CauA(inValue);
            return retVal.Body.CauAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsole.Xuly.CauBSoChanResponse ClientConsole.Xuly.ServiceSoap.CauBSoChan(ClientConsole.Xuly.CauBSoChanRequest request) {
            return base.Channel.CauBSoChan(request);
        }
        
        public string CauBSoChan(int a, int b, int c, int d, int e) {
            ClientConsole.Xuly.CauBSoChanRequest inValue = new ClientConsole.Xuly.CauBSoChanRequest();
            inValue.Body = new ClientConsole.Xuly.CauBSoChanRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            inValue.Body.d = d;
            inValue.Body.e = e;
            ClientConsole.Xuly.CauBSoChanResponse retVal = ((ClientConsole.Xuly.ServiceSoap)(this)).CauBSoChan(inValue);
            return retVal.Body.CauBSoChanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsole.Xuly.CauBSoLeResponse ClientConsole.Xuly.ServiceSoap.CauBSoLe(ClientConsole.Xuly.CauBSoLeRequest request) {
            return base.Channel.CauBSoLe(request);
        }
        
        public string CauBSoLe(int a, int b, int c, int d, int e) {
            ClientConsole.Xuly.CauBSoLeRequest inValue = new ClientConsole.Xuly.CauBSoLeRequest();
            inValue.Body = new ClientConsole.Xuly.CauBSoLeRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            inValue.Body.d = d;
            inValue.Body.e = e;
            ClientConsole.Xuly.CauBSoLeResponse retVal = ((ClientConsole.Xuly.ServiceSoap)(this)).CauBSoLe(inValue);
            return retVal.Body.CauBSoLeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientConsole.Xuly.SNTResponse ClientConsole.Xuly.ServiceSoap.SNT(ClientConsole.Xuly.SNTRequest request) {
            return base.Channel.SNT(request);
        }
        
        public ClientConsole.Xuly.ArrayOfInt SNT(int a, int b, int c, int d, int e) {
            ClientConsole.Xuly.SNTRequest inValue = new ClientConsole.Xuly.SNTRequest();
            inValue.Body = new ClientConsole.Xuly.SNTRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            inValue.Body.c = c;
            inValue.Body.d = d;
            inValue.Body.e = e;
            ClientConsole.Xuly.SNTResponse retVal = ((ClientConsole.Xuly.ServiceSoap)(this)).SNT(inValue);
            return retVal.Body.SNTResult;
        }
    }
}
